### ISSUE TITLE
Error when running node .aws

### ISSUE THREAD

**Issue by FoldedLettuce** [jcbrian/awsProxyGen#1]
I get this error when i run node .aws
`PS C:\Users\Liam\Desktop\Proxy Gen> node .aws
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\Liam\Desktop\Proxy Gen\.aws'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

**Comment by jcbrian** [comment]
It's just node aws, no period before it
